### ISSUE TITLE
KAMP ignores my bicubic_tension value

### ISSUE THREAD

**Issue by hashraid** [kyleisah/Klipper-Adaptive-Meshing-Purging#136]
**Describe the issue**
Whenever the print is big enough for bicubic algorithm to be used, it is overwriting my bicubic tension value and reverting to standard value of 0.2

**What slicer are you using?**
Orcaslicer

Slice of printer.cfg:

[bed_mesh]
speed: 400
probe_count: 10, 10
horizontal_move_z: 5
algorithm: bicubic
bicubic_tension: 0.5
mesh_min : 20, 20
mesh_max : 450, 405
mesh_pps: 3, 3

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [extruder]
#*# control = pid
#*# pid_kp = 26.028
#*# pid_ki = 1.157
#*# pid_kd = 146.410
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	0.712500, 0.695000, 0.722500, 0.775000, 0.837500, 0.882500, 0.917500, 0.962500, 1.030000, 1.157500
#*# 	0.755000, 0.672500, 0.635000, 0.592500, 0.632500, 0.690000, 0.747500, 0.822500, 0.917500, 1.087500
#*# 	0.732500, 0.592500, 0.490000, 0.422500, 0.410000, 0.450000, 0.525000, 0.660000, 0.832500, 1.025000
#*# 	0.717500, 0.537500, 0.382500, 0.267500, 0.220000, 0.260000, 0.342500, 0.512500, 0.712500, 0.932500
#*# 	0.715000, 0.517500, 0.372500, 0.262500, 0.187500, 0.252500, 0.340000, 0.512500, 0.705000, 0.927500
#*# 	0.720000, 0.562500, 0.415000, 0.290000, 0.232500, 0.280000, 0.397500, 0.540000, 0.735000, 0.962500
#*# 	0.712500, 0.560000, 0.432500, 0.337500, 0.287500, 0.307500, 0.377500, 0.525000, 0.722500, 0.925000
#*# 	0.752500, 0.610000, 0.522500, 0.440000, 0.400000, 0.432500, 0.512500, 0.597500, 0.770000, 0.982500
#*# 	0.840000, 0.732500, 0.660000, 0.630000, 0.630000, 0.685000, 0.712500, 0.787500, 0.907500, 1.067500
#*# 	0.885000, 0.815000, 0.825000, 0.870000, 0.987500, 1.030000, 1.025000, 1.020000, 1.075000, 1.215000
#*# x_count = 10
#*# y_count = 10
#*# mesh_x_pps = 3
#*# mesh_y_pps = 3
#*# algo = bicubic
#*# tension = 0.2
#*# min_x = 20.0
#*# max_x = 449.93
#*# min_y = 20.0
#*# max_y = 404.93

**Comment by kyleisah** [comment]
Klipper does not currently support adjusting the tension during runtime. All of KAMPs adjustments are calculated and output as a bed_mesh_calibrate command with options that klipper allows adjustments for. 

Those can be found here:
https://www.klipper3d.org/Bed_Mesh.html#bed-mesh-gcodes

My guess is, since KAMP has the ability to define what algorithm will be used, default values for such algorithms are called.

If the bicubic tension being 0.5 is something you can't live without, then it's probably best to open an issue at Klipper's github and ask for the ability to define bicubic tension with the BED_MESH_CALIBRATE command.

There's nothing I can do for you here currently, unfortunately.
