### ISSUE TITLE
VOROn_Purge code error

### ISSUE THREAD

**Issue by mcfool12** [kyleisah/Klipper-Adaptive-Meshing-Purging#192]
The Voron_Purge.cfg file has an error with the line 

G1 X{purge_x_origin+size*0.289} Y{purge_y_origin+size} E{purge_amount/4} F{purge_move_speed}# Purge first line of logo

There needs to be a space for the comment to work.  It is editable but then the repo is dirty in Klipper.

**Comment by kyleisah** [comment]
Just to clarify, the macro works, but because of the space there the syntax highlighting looks wrong? I can fix that easily if so On Oct 6, 2023, at 7:56 AM, mcfool12 ***@***.***> wrote:﻿
The Voron_Purge.cfg file has an error with the line
G1 X{purge_x_origin+size*0.289} Y{purge_y_origin+size} E{purge_amount/4} F{purge_move_speed}# Purge first line of logo
There needs to be a space for the comment to work.  It is editable but then the repo is dirty in Klipper.

**Comment by mcfool12** [comment]
It worked but would freeze after the third line, for about 15 seconds after making the purge, for me for some reason.  It started after applying the latest update, not sure if that is when it was changed.  Once I added the space it was back to working normally.

**Comment by kyleisah** [comment]
That's really odd. But I will go ahead and make the changes now.

**Comment by kyleisah** [comment]
There we are, changes are made and update's pushed.

**Comment by mcfool12** [comment]
Thanks
