### ISSUE TITLE
Print_Start content?

### ISSUE THREAD

**Issue by 110Tim706** [kyleisah/Klipper-Adaptive-Meshing-Purging#5]
So what i did:
- downloaded both cfg files
- uploaded them to the config section
- included them in printer.cfg 
- pasted:

[file_manager]
enable_object_processing: True

in moonraker.conf
- pasted [exclude_object] in printer.cfg

Double check your PRINT_START macro to ensure BED_MESH_CALIBRATE and/or ADAPTIVE_PURGE macros are defined.
haven't got thisas macro so far. What do i need to write in it?

**Comment by 110Tim706** [comment]
what needs to be  in print_start?

**Comment by 110Tim706** [comment]
Had to configure the macro.

[gcode_macro PRINT_START]
gcode:
  BED-MESH-CALIBRATE

**Comment by kyleisah** [comment]
@110Tim706 

Oh I see, so it sounds like you've usually just used the slicer's start gcode section instead of having a print_start macro in Klipper?

Having a Print_Start macro is honestly ideal because then you can expect the same behavior from your machine regardless of what slicer you use. 😄 

Here's this link which will give you some more information:
https://www.klipper3d.org/Slicers.html#klipper-gcode_macro
