### ISSUE TITLE
[Feature Request] Configurable Purge Line Direction (X or Y axis)

### ISSUE THREAD

**Issue by cinadr** [kyleisah/Klipper-Adaptive-Meshing-Purging#58]
Hi!

It would be nice to have purge line configurable to print along X or Y axes. It is currently on X axis and it is obstructing my camera view of the first layer. All my slicers have purged along Y axis before so as my former klipper START macro. I managed to change manually within gcode_macro LINE_PURGE line 57 to
` G0 X{x_origin - distance_to_object_y} Y{y_origin}                                   # Move to purge position`
and line 60
`G1 Y{y_origin + line_length} E{purge_amount} F{purge_move_speed}                    # Purge line`
I have no experience in macro parameters so I cannot do a pull request. 
This blows away my moonraker plugin update as the plugin gets dirty with this workaround.

**Comment by kyleisah** [comment]
Ah, yeah, I kinda thought about this too. In dev I've made the line_purge macro be centered along X in front of the print. I don't imagine it would be hard to make it do the same thing for Y. I'll be sure to try that out and see what I can come up with. The dev branch is a little bit of a mess so this feature will have to wait until dev is all finished up, but I'll see what I can do!

Might be cool to make it so if it can't purge along X because there's no room, it'll purge along Y. 😄

**Comment by LadPack** [comment]
An idea along these same lines, I tried using the Purge line with a Delta printer, and it printed the purge line into the part itself, I think having it adjust the purge line could be really cool.
