### ISSUE TITLE
Add Adaptive Probe Count

### ISSUE THREAD

**Issue by ChaosBlades** [kyleisah/Klipper-Adaptive-Meshing-Purging#6]
When printing parts with a very large first layer I run a 9x9 mesh due to a hilly bed but this is massive overkill for printing a tiny part. If the part is small enough even 1 point will do. So it would bring this macro to the next level if it could set a minimum and maximum probe count. There is no point in meshing 9x9 just to print a benchy on a 350mm bed for example. A simple 3x3 is more than enough

I think this macro has this functionality.
https://gist.github.com/ChipCE/95fdbd3c2f3a064397f9610f915f7d02

**Comment by kyleisah** [comment]
As it is right now, whatever you have set as your `probe_count` under `[bed_mesh]` in `printer.cfg` will be the maximum probe count, and KAMP will adaptively scale it. Typically it will make a 3x3 as the smallest, or even smaller depending.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/40312912/204155008-e58fc4ea-1330-4351-a7f4-e60c287d176a.png">

You can see here how the maximum is determined in Adaptive_Mesh.cfg. 

I don't think having a minimum makes sense, because the point is to have a small and rich mesh rather than a large and wasteful mesh.

**Comment by kyleisah** [comment]
Also, a 1 point mesh isn't really a mesh. You could just home Z to the center of the print area instead and not run a mesh, but I tend to think most people who don't use a bed mesh wouldn't want an adaptive mesh

**Comment by ChaosBlades** [comment]
Your right, I didn't notice it actually does adjust the mesh size. 

Should have read more closely.

> KAMP made a mesh that is 7x4

**Comment by Kosh42** [comment]
I came here to request this exact feature. Excellent that it is already in place.

I may try and create a pull request later to make it more explicit in the docs so people don't raise it in future.

KAMP is an awesome invention. Thanks for sharing your hard work with the community.
